# This workflow triggers on pull request events

name: "Pull Request"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Pull Request Reviewer
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Review PR
        uses: vermwestling/pull-request-reviewer@main
        with:
          api-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'gpt-4o'
          review-type: 'PR comment'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
