# This workflow triggers on pull request events

name: "Pull Request"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Pull Request Reviewer
    steps:
      - name: Review PR
        uses: vermwestling/pull-request-reviewer@main
        with:
          api-endpoint: 'https://my-api-endpoint.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
