# This workflow triggers on pull request events

name: "Pull Request"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    name: Pull Request Reviewer
    steps:
      - name: Review PR
        uses: vermwestling/pull-request-reviewer@main
